[workspace]
members = ["rustorio-derive", "rustorio-engine", "rustorio"]
resolver = "3"

[workspace.package]
version = "0.1.1"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/albertsgarde/rustorio"

[workspace.lints.clippy]
missing_const_for_fn = "warn"
