[workspace]
members = ["rustorio-derive", "rustorio-engine", "rustorio"]
resolver = "3"

[workspace.package]
version = "0.0.5"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/albertsgarde/rustorio"
